import Head from 'next/head'
import {Inter} from '@next/font/google'
import styles from '../styles/Home.module.scss'
import About from "./about";
import Projects from "./projects";
import Contact from "./contact";
import Landing from "./landing";

export default function Home() {
    return (
        <>
            <Head>
                <title>Developer Portfolio</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <h1>Developer Portfolio</h1>

                {/*<div>*/}
                {/*<div className="hero">*/}
                {/*    <h1>Developer Name</h1>*/}
                {/*</div>*/}
                {/* Add other sections here */}
                {/*</div>*/}

                <div id={'landing-page'}>
                    <Landing/>
                </div>

                <div id={'about-page'}>
                    <About/>
                </div>

                <div id={'projects-page'}>
                    <Projects/>
                </div>

                <div id={'contact-page'}>
                    <Contact/>
                </div>
            </main>
        </>
    )
}
